/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.C_Compras;
import Controller.C_Fornecedor;
import DAO.Compras;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Usuario
 */
public class V_Compras_Atualizacao extends javax.swing.JFrame {

    /**
     * Creates new form V_Compras
     */
    public V_Compras_Atualizacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCompraNumNota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxComprasIDFornecedor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextComprasData = new javax.swing.JFormattedTextField();
        ButtonComprasSalvar = new javax.swing.JToggleButton();
        ButtonComprasSair = new javax.swing.JToggleButton();
        ButtonComprasExcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextComprasID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Compras");

        jLabel2.setText("Numero da Nota");

        jTextCompraNumNota.setName(""); // NOI18N
        jTextCompraNumNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCompraNumNotaActionPerformed(evt);
            }
        });

        jLabel3.setText("Id Fornecedor");

        jComboBoxComprasIDFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxComprasIDFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxComprasIDFornecedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Compra");

        jTextComprasData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        ButtonComprasSalvar.setText("Salvar");
        ButtonComprasSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonComprasSalvarActionPerformed(evt);
            }
        });

        ButtonComprasSair.setText("Sair");

        ButtonComprasExcluir.setText("Excluir");
        ButtonComprasExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonComprasExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("ID Compras");

        jTextComprasID.setName(""); // NOI18N
        jTextComprasID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextComprasIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCompraNumNota)
                            .addComponent(jComboBoxComprasIDFornecedor, 0, 171, Short.MAX_VALUE)
                            .addComponent(jTextComprasData)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(ButtonComprasSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonComprasExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonComprasSair))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jTextComprasID)))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextComprasID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextCompraNumNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxComprasIDFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextComprasData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonComprasSalvar)
                    .addComponent(ButtonComprasSair)
                    .addComponent(ButtonComprasExcluir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCompraNumNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCompraNumNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCompraNumNotaActionPerformed

    private void jComboBoxComprasIDFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxComprasIDFornecedorActionPerformed
        C_Fornecedor cf = new C_Fornecedor();  
            List<Object[]> fornecedores = cf.consulta();
            for(Object[] fornecedor:  fornecedores){  
                String inf = new String(fornecedor[0]+" "+fornecedor[1]);
                jComboBoxComprasIDFornecedor.addItem(inf);
            }
    }//GEN-LAST:event_jComboBoxComprasIDFornecedorActionPerformed

    private void ButtonComprasSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonComprasSalvarActionPerformed
        Compras c = new Compras();        
        c.setNumNota(jTextCompraNumNota.getText());
        //pegando o id
        String forn = (String)jComboBoxComprasIDFornecedor.getSelectedItem();
        String[] vetor = forn.split(" ");
        Integer id = Integer.parseInt(vetor[0]);
        c.setIdForn(id);
        //Isso foi o mais perto que eu achei para converter data, naõ sei se está certo.
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        Date d = null;
        try {
            d = sdf.parse(jTextComprasData.getText());
        } catch (ParseException ex) {
            Logger.getLogger(V_Compras_Atualizacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setDataCompra(d);
        c.setIdCompra(Integer.parseInt(jTextComprasID.getText()));
        
        C_Compras cc = new C_Compras();
        cc.salvar(c);
    }//GEN-LAST:event_ButtonComprasSalvarActionPerformed

    private void ButtonComprasExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonComprasExcluirActionPerformed
        // TODO add your handling code here:
         C_Compras cc = new C_Compras();
        cc.excluir(Integer.parseInt(jTextComprasID.getText()));
    }//GEN-LAST:event_ButtonComprasExcluirActionPerformed

    private void jTextComprasIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextComprasIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextComprasIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Compras_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Compras_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Compras_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Compras_Atualizacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Compras_Atualizacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonComprasExcluir;
    private javax.swing.JToggleButton ButtonComprasSair;
    private javax.swing.JToggleButton ButtonComprasSalvar;
    private javax.swing.JComboBox<String> jComboBoxComprasIDFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextCompraNumNota;
    private javax.swing.JFormattedTextField jTextComprasData;
    private javax.swing.JTextField jTextComprasID;
    // End of variables declaration//GEN-END:variables
}
